### ISSUE TITLE
Redis NOAUTH authentication required

### ISSUE THREAD

**Issue by AkshayPilane** [mainflux/devops#122]
On Mainflux Deploying we are facing certain problems in api's for e.g. 
Not able to remove things, on checking thing pod logs.  its displaying error `NOAUTH authentication required`.

On debugging redis DB,
Tried perform redis db commands e.g. KEYS *
but gives error as `NOAUTH authentication required`.

On checking environment variables for redis pod, there are env variable as following `REDIS_PASSWORD=<REDIS_PASSWORD>`.
and after loging in redis db and using `REDIS_PASSWORD` with command `auth <username> <REDIS_PASSWORD>`
all commands are working without error.

could this be issue with redis connection ?

**Comment by drasko** [comment]
@arvindh123 why is this closed without any explication?
