### ISSUE TITLE
Document minikube instructions

### ISSUE THREAD

**Issue by beriberikix** [mainflux/devops#18]
Would it be possible to get deployment instructions for `minikube`? I believed I setup everything correctly (including the ingress addon) but half my pods end up in an error state. Thanks!

**Comment by nmarcetic** [comment]
@beriberikix Basically all you need to do is helm install, as described [here](https://github.com/mainflux/devops/tree/master/charts/mainflux), that's it. If your pods failing, its probably something with your minikube, its hard to helm here, especially without any log trace :) 
We will write detailed howto step by step, but it will not be related to minikube, more like K8s in general (having running cluster or minikube is request).

**Comment by drasko** [comment]
@beriberikix if you write a Medum blog, let us know and we will publish it. Until then closing this issue.

**Comment by beriberikix** [comment]
Looks like Jaeger was the culprit.

```
jonathanberi:charts 🚀 $ kubectl logs mainflux-1582124392-adapter-coap-d6f7b5c7f-n8wpx 
...
{"level":"error","message":"Failed to init Jaeger client: lookup \
mainflux-1582124392-jaeger-operator-jaeger-agent on 10.96.0.10:53: no such \
host","ts":"2020-02-19T15:16:33.331888432Z"}

jonathanberi:charts 🚀 $ kubectl logs mainflux-1582124392-jaeger-operator-5f4846b8c-h4r6r 
...
time="2020-02-19T15:00:58Z" level=error msg="failed to apply the changes" \
error="ConfigMap \"mainflux-1582124392-jaeger-operator-jaeger-sampling-configuration\"\
 is invalid: metadata.labels: Invalid value: \
"mainflux-1582124392-jaeger-operator-jaeger-sampling-configuration\": \
must be no more than 63 characters" execution="2020-02-19 15:00:58.129296608 +0000 UTC" \
instance=mainflux-1582124392-jaeger-operator-jaeger namespace=default
```

When I run `helm install mf ./mainflux/ --dependency-update` (not `--generate-name`,) I don't get any errors.

**Comment by nmarcetic** [comment]
Awesome @beriberikix ;) Glad its working now! Anyway, we will provide step by step doc ASAP, even if it's super easy to run it :) As @drasko suggested if you are willing to make a blog post on Medium like "Running Mainflux on Minikube", with your impressions ofc, that would be great!

**Comment by beriberikix** [comment]
Next thing I need to figure out is how to configure `minikube`'s ingress to work with all the ports configured by these yaml files. These a fair bit to parse :)
