### ISSUE TITLE
Optional services 

### ISSUE THREAD

**Issue by nmarcetic** [mainflux/devops#20]
Is there a way to do the optional installation of some services? For example, I don't want WS adapter or CoAP so they can be optional during helm install.

**Comment by blokovi** [comment]
Let's start with making non-core services optional. For now, that are influxdb reader & writer (and influxdb database itself). All non-core services we will add later should be optional also.
Influx services will be enabled with `--set influxdb.enabled=true`

**Comment by nmarcetic** [comment]
@blokovi Great! I saw PR #50

**Comment by nmarcetic** [comment]
@blokovi Agree, that make sense. Not sure about UI, maybe is good idea to have it as part of Core (its not add-on, it's just in another repository). Although I think Mainflux should stay lightwate and client agnostic I think it would be good to run UI as part of Core in helm chart.

**Comment by nmarcetic** [comment]
@blokovi I am also thinking about chart dependencies and umbrella charts. Thing to think about in for #later or next stage of refactoring,

We can scope Core services and make mainflux/core chart as the main chart. Creat micro charts for each add-on that we have and mark them with a condition: optional, then import them in core chart. Each micro chart will have mainflux/core marked as a dependency (you can't run grafana add-on without core). 
This way we will avoid hardcoded conditions like if/else in the chart, which grows all the time and will become hard to maintain.
We also get [tagging](https://v2.helm.sh/docs/chart_best_practices/#conditions-and-tags) and version management simpler. 
People get install only core or upgrade only add-ons without touching core release. It's much more flexible.
It will be much easier to maintain and develop if we decouple it.

**Comment by blokovi** [comment]
I agree, umbrella charts sounds good. I have already make add-ons (influxdb and bootstrap) optional in PR #50 that will close this issue when it's merged. We will continue conversation about umbrella charts in new issue.
