### ISSUE TITLE
Add VerneMQ data volume 

### ISSUE THREAD

**Issue by nmarcetic** [mainflux/devops#27]
In order to have persistency, we need to map volume [like this](https://github.com/vernemq/docker-vernemq/blob/master/helm/vernemq/templates/statefulset.yaml#L104). We don't need persistent logs, but data for sure :)

**Comment by drasko** [comment]
Data is currently persisted in RAM, and I think it is safe to keep it this way, then parameterize system for an expected load.

@blokovi can this one be closed?

**Comment by nmarcetic** [comment]
@drasko What do you mean by safe? It's not production-ready if you keep data in RAM. 
You have persistency for other data, like DB's why not for messaging?
