### ISSUE TITLE
MQTT over WS

### ISSUE THREAD

**Issue by nmarcetic** [mainflux/devops#30]
Add support for MQTT  over WS with the latest mproxy integration. Latest `mainflux/mqtt` image is tagged as `0.10.1` and pushed to [docker hub](https://hub.docker.com/layers/mainflux/mqtt/0.10.1/images/sha256-6877241fbe213072000646d28cc6c8a1b67eac6022d9e3416959d6b3f1dd58c6?context=explore)

**Comment by drasko** [comment]
@nmarcetic can this one be closed? Which commit closes it?

**Comment by nmarcetic** [comment]
Yes, [this one](https://github.com/mainflux/devops/pull/33)
