### ISSUE TITLE
MQTTS not working

### ISSUE THREAD

**Issue by nmarcetic** [mainflux/devops#32]
Not sure about mTLS but MQTTS port is not exposed at all.

**Comment by drasko** [comment]
@nmarcetic can you please add some data here and resolve this bug?

**Comment by blokovi** [comment]
About exposing ports: nginx-ingress service is prerequisites for mainflux deployment with helm charts. Ingress service must be edited to add ports `1883` and `8883` and also proxy protocol must be inabled on ingress. 
I will leave this issue open until this is documented.
Also mTLS must be tested.
