### ISSUE TITLE
Not possible for LoadBalancer to listen on both TCP and UDP ports

### ISSUE THREAD

**Issue by blokovi** [mainflux/devops#66]
Kubernetes does not currently allow multiprotocol LoadBalancer services.
Nginx-ingress controller should listen on UDP port and route to CoAP adapter on backend.

Research possible solution:
https://github.com/influxdata/helm-charts/pull/194

**Comment by blokovi** [comment]
Another note about this problem, since Kubernetes 1.20 there is feature gate `MixedProtocolLBService` that enables using different protocols in the same LoadBalancer type Service instance.
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by drasko** [comment]
@blokovi any news on this one?

**Comment by blokovi** [comment]
@drasko Since Kubernetes 1.24 `MixedProtocolLBService` is enabled by default. That means now it's enabled using different protocols in the same LoadBalancer type Service instance. 
I would close this issue

**Comment by dborovcanin** [comment]
Closing with https://github.com/mainflux/devops/issues/66#issuecomment-1229955759.
