### ISSUE TITLE
jaeger-operator creates conflicting Ingress resource

### ISSUE THREAD

**Issue by rickardgranberg** [mainflux/devops#67]
I'm testing out Mainflux and when I deployed using the Helm chart, I noticed that I could not reach the Mainflux UI. Instead I got the Jaeger query ui presented when browsing to http://localhost (I'm running this locally using Docker Desktop with K8s)
When inspecting the deployment, I noticed that in addition to the three Mainflux ingresses, there's a fourth one created by the Jaeger-operator. 
The Mainflux UI is using the / as path, and the Jaeger-operator doesn't state one (which means that it defaults to /) which is what is causing the problem.

I used the following command line when installing the chart:
`helm install --kube-context docker-desktop --namespace mf --create-namespace mainflux . --set defaults.replicaCount=1 --set nats.replicaCount=1 --set twins.enabled=true --set influxdb.enabled=true`

**Comment by blokovi** [comment]
That's right, you will need to set also hostname for mainflux ingress with: 
```--set ingress.hostname='example.com'```
Also set A record for that host to point to external IP address of ingress-controller service. Then mainflux UI will be open on `example.com` 
I recommend you to go through  [kubernetes chapter in docs](https://mainflux.readthedocs.io/en/latest/kubernetes/) if you haven't already.

**Comment by rickardgranberg** [comment]
I did read through it but I interpreted the `--set ingress.hostname='example.com'` as optional, especially since I was running it up locally on my machine. I was being to clever I guess. It works now when I add that. Thank you !
