### ISSUE TITLE
Fix naming in MQTT statefulset

### ISSUE THREAD

**Issue by blokovi** [mainflux/devops#73]
Naming of several resources are misleading or can be confusing within MQTT stateful set:
- it's statefulset but filename is `adapter_mqtt-deployment.yaml`, file name shoud be renamed from `deployment` to `statefulset`
-  container created (by default) from image `mainflux/vernemq` is named `mainflux-adapter-mqtt`, better name for this is `broker` then `adapter`
- container created from image `mainflux/mqtt` is named `mainflux-mqtt-proxy`. This is partilly correct, but a more accurate term would be `adapter` instead of `proxy`
- statefulset containing the above two containers is named `mainflux-adapter-mqtt`. That is maybe ok, but if we rename proxy to adapter, that could be confusing

**Comment by dusanb94** [comment]
I think that filename, as well as renaming VerneMQ container to `mqtt-broker` and MQTT adapter to `mqtt-adapter` is fine. The only remaining question is the statefulset. Maybe simply `mainflux-mqtt`?

**Comment by blokovi** [comment]
> I think that filename, as well as renaming VerneMQ container to `mqtt-broker` and MQTT adapter to `mqtt-adapter` is fine. The only remaining question is the statefulset. Maybe simply `mainflux-mqtt`?

I like this solution for statefulset `mainflux-mqtt`, (actually it would be `{{ .Release.Name }}-mqtt`). The simplest solution is always best.
Just note - name of deployments for other adapters are `mainflux-adapter-coap` `mainflux-adapter-http` so for the sake of consistency I would just reverse the order of the words in your proposal.

So:
`mainflux-mqtt` = `mainflux-broker-mqtt` + `mainflux-adapter-mqtt`

**Comment by manuio** [comment]
I agree for `mainflux-mqtt = mainflux-broker-mqtt + mainflux-adapter-mqtt`
