### ISSUE TITLE
Add ingress for things groups

### ISSUE THREAD

**Issue by manuio** [mainflux/devops#93]
There are endpoints in Things and Users service to create groups but currently ingress is only configured for Users groups. 
We can probably use: 
```
/groups/users
/groups/things
```
or
```
/groups-users
/groups-things
```

**Comment by drasko** [comment]
Add issue to core as well

**Comment by blokovi** [comment]
In docker-compose it's ```groups/things``` and ```groups/users``` so I would go the same here.

https://github.com/mainflux/mainflux/blob/master/docker/nginx/nginx-key.conf#L73
